name: Upload and Download Artifact 

on: push 

jobs:
  upload-artifact:
    runs-on: ubuntu-latest 
    steps:
      - name: Make Artifact 
        run: |
          echo "This is an artifact by Ayesha Azad." >> artifact.txt
          echo "Generated on $(date)." >> artifact.txt
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: artifact-example
          path: artifact.txt
  download-artifact: 
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download Artifact 
        uses: actions/download-artifact@v4
        with: 
          name: artifact-example
      - name: View File
        run: cat artifact.txt
