name: Checking Composite Actions 

on: push

jobs:
  hello-ayesha:
    runs-on: ubuntu-latest
    steps:
      - name: Check Code 
        uses: actions/checkout@v4
      - name: Greetings
        uses: ./.github/actions/composite-action
        with:
          greetings: "Ayesha Azad"
      - name: Random Number Generated
        id: composite-num-gen
        uses: ./.github/actions/composite-action
        env:
          RANDOM_NUM :  ${{steps.composite-num-gen.outputs.random}}
        run: echo "Random number is $RANDOM_NUM" 
