name: Checking Composite Actions 

on: push

jobs:
  hello-ayesha:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        uses: ./actions/composite-action
        with:
          greetings: "Ayesha Azad"
      - name: Random Number Generated
        id: composite-num-gen
        uses: ./actions/composite-action
        
