name: Different Events

on:
  # push:
  #   branches:
  #     - 'examples/*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "filters/*.md"
      - "!filters/*.txt"

  schedule:
    - cron: "35 13 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Events"
        run: echo "This job will check events."
