name: Environment Variables

on: push

env:
  $WORKFLOW_ENV: 'Workflow Environment Variable'
  
jobs:
  job1:
    env:
      $JOB_ENV: 'Job Environment Variable'
    runs-on: ubuntu-latest
    steps:
      - name: "First Job"
        env:
          $STEP_ENV: 'Step Environment Variable'
        run: |
          echo "This is the $STEP_ENV"
          echo "This is the $JOB_ENV"
          echo "This is the $WORKFLOW_ENV"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: "Second Job"
        run: |
          echo "This is the $STEP_ENV"
          echo "This is the $JOB_ENV"
          echo "This is the $WORKFLOW_ENV"
