name: Reused Workflow 

on: push 

jobs: 
  hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello Ayesha Azad 
        uses: ./.github/workflows/reusable-workflow.yaml
        with: 
          name: "Ayesha Azad"
