name: Reusable Workflow 

on: 
  workflow_call:
    inputs: 
      name: 
        default: "Ayesha"
        required: true 
        type: string

jobs:
  hello-ayesha:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello ${{inputs.name}}"
