name: Reusable Workflows

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        default: Ayesha
        type: string

jobs: 
  hello-ayesha:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello Ayesha"
        run: echo "Hello ${{inputs.name}}"
