name: Secrets and Environment Variables

on: push

jobs:
  staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}
    steps:
      - name: "Check Staging Variables and Secrets"
        run: | 
          echo "Environment secret at staging is $EXAMPLE_ENVIRONMENT_SECRET"
          echo "Environment variable at staging is $EXAMPLE_ENVIRONMENT_VARIABLE"
          echo "Repository secret at staging is $EXAMPLE_REPOSITORY_SECRET"
          echo "Repository variable f at staging is $EXAMPLE_REPOSITORY_VARIABLE"
      
  production:
    runs-on: ubuntu-latest
    environment: production
    env:
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}
    steps:
      - name: "Check Production Variables and Secrets"
        run: | 
          echo "Environment secret at production is $EXAMPLE_ENVIRONMENT_SECRET"
          echo "Environment variable at production is $EXAMPLE_ENVIRONMENT_VARIABLE"
          echo "Repository secret at production is $EXAMPLE_REPOSITORY_SECRET"
          echo "Repository variable f at production is $EXAMPLE_REPOSITORY_VARIABLE"
